version: 2
sources:
  - name: finance
    tables:
      - name: trades
        description: >
          One record per trade made, includes the broker used and price of the sale or buy
        columns:
          - name: broker
            description: Broker at which the trade was executed
          - name: stock
            description: Full stock name which was traded
          - name: isin
            description: ISIN number of the traded stock
          - name: amount
            description: Number of shares involved in transaction
          - name: price
            description: Price per share for the transaction
          - name: type
            description: Was this a buy or sell transaction
          - name: filed_at
            description: When the order was placed with the broker
          - name: executed_at
            description: When the broker confirmed the trade was executed